version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ocr_redis
    ports:
      - "6378:6379"
    restart: always

  api:
    build: .
    container_name: ocr_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    depends_on:
      - redis

  worker:
    build: .
    container_name: ocr_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    depends_on:
      - redis
